### ISSUE TITLE
Adding Component Names to DataSetInfo

### ISSUE THREAD

**Issue by JAWilliams123** [phmkopp/vtu11#45]
Hello,

Many thanks for making this project publicly available, it is brilliant.. Is it possible to include the individual component names for dataSets, e.g., for a displacement field with 3 components Ux, Uy and Uz where the DataSetInfo is specified as { "Displacement", vtu11::DataSetType::PointData, 3 }, I would like to be able to name the individual components.

Many thanks,
JWilliams

**Comment by phmkopp** [comment]
Hello JWilliams,

sorry for not replying earlier ... I didn't get any email notifications, I'll have to fix that.

First of all, thanks for the praise, we appreciate that a lot :)

To your suggestion: what do you think about adding the following overload
```cpp
template<typename MeshGenerator>
void writeVtu( const std::string& filename,
               MeshGenerator& mesh,
               const std::vector<DataSetType>& dataSetTypes,
               const std::vector<StringStringMap>& dataSetAttributes,
               const std::vector<DataSetData>& dataSetData,
               const std::string& writeMode = "RawBinaryCompressed" );
```
where we pass the `DataSetType` (whether it's point or cell data) separately and then have a vector of std::map<std::string, std::string> that allows you to pass any attributes that will directly be written to the xml file.

This could then look roughly something like this:
```cpp
auto types = std::vector { vtu11::DataSetType::PointData, vtu11::DataSetType::PointCell };

auto attributes1 = StringStringMap { { "Name" : "Displacement" }, 
                                     { "ComponentName0" : "Ux" },
                                     { "ComponentName1" : "Uy" },
                                     { "ComponentName2" : "Uz" } };

auto attributes2 = StringStringMap { { "Name" : "YoungsModulus" } }; // implies only one component
   
vtu11::writeVtu( "test.vtu", mesh, types, {attributes1, attributes1}, {pointData, cellData}, "Ascii" );
```

This may provide the most flexibility for the least amount of effort. And of course, we would need to overload `writePVtu` and `writePartition` as well.

What do you think?

Philipp

**Comment by JAWilliams123** [comment]
Hello Philipp,

Many thanks for the feedback. I actually went ahead and made some modifications to get things up and running today. But I think my changes may not be as elegant as what you have proposed. I made the following changes:

1. I adjusted the DataSetInfo tuple to include the component names:

```c++
using DataSetInfo = std::tuple<std::string, DataSetType, size_t, std::vector<std::string>>;
```

2. I created an overloaded `writeDataSet`

```c++
void writeDataSet( Writer& writer,
                   std::ostream& output,
                   const std::string& name,
                   size_t ncomponents,
                   const std::vector<DataType>& data,
                   const std::vector<std::string>& component_names)
{
    auto attributes = writeDataSetHeader<DataType>( writer, name, ncomponents, component_names );
 .... 
}
```
3. Finally, I created an overloaded `writeDataSetHeader`. This allows me to include the components names from `dataSetInfo` as shown below. This way I stick to the same general input style of vtu11.

```c++
StringStringMap writeDataSetHeader( Writer&& writer,
                                    const std::string& name,
                                    size_t ncomponents,
                                    const std::vector<std::string>& component_names)
{
    StringStringMap attributes = { { "type", dataTypeString<DataType>( ) } };
    if( name != "" )
    {
        attributes["Name"] = name;
    }
    if( ncomponents > 1 )
    {
        attributes["NumberOfComponents"] = std::to_string( ncomponents );    
        for (const auto& iter : component_names)
        {
            const auto comp_no = &iter - &component_names[0];
            attributes [" ComponentName" + std::to_string(comp_no)] = iter;
        }
    }
    writer.addDataAttributes( attributes );
    return attributes;
```

Within my code I build `dataSetInfo` by adding the `std::vector<std::string>` containing the component names as shown below:

```c++
dataSetInfo.push_back({fname_iter,vtu11::DataSetType::PointData,num_comps,fname_comp});
```
I can actually process and create vtu binary files from a 3.5GB Calculix output frd file in 2 minutes with the help of vtu11. Thanks so much again for making the project freely available....it is just brilliant.

Many thanks,
JW

**Comment by phmkopp** [comment]
Hello JWilliams,

that's awesome :) I'm glad that our code helps you. We (@philbucher and me) realized that we both separately wanted to write vtu files without depending on the vtk libraries and making our code public was really no additional effort. And we both have benefited from other people's work in the past too.

I think your approach is straight forward and I was considering something along those lines too. The reasons I thought about an alternative are:
- Changing the definition of `DataSetInfo` is not backwards compatible. Although we don't have many users, I know a couple of people who use our code and I would prefer not to break the interface for them.
- Data sets do not always have multiple components and having to give a component name for a data set without components is somewhat counter intuitive.
- The ability to specify component names is not well documented (at least I didn't see any info until I looked into the vtk source code). This makes me wonder what other attributes people may want to pass in the future, and having a generic way of handling them makes sense to me.

I can look into it the next couple of days. If I understand you correctly, my attribute string-map solution would work for you as well, right?

Philipp

**Comment by JAWilliams123** [comment]
Hello Philipp,

Yes, I believe that the attribute string-map solution may work. In my case it needs to be something that I can build over a loop for the various components that are stored in my output file. I do like the idea of having compressed output files so perhaps if this is something that vtu11 can accomplish without needing zlib that would be wonderful.

Best wishes,
JW

**Comment by JAWilliams123** [comment]
Philipp,

Many thanks again. I would appreciate a copy of the Python code. I will also close off this issue with your next response as I am happy with the feedback provided on the query raised.

Best wishes,
JW

**Comment by phmkopp** [comment]
Hello JW,

if I understand you correctly, then you have found your solution and you don't need us to update vtu11 at the moment, is that corrrect?

I have checked my python implementation and realized that it is somewhat incomplete. I implemented the compression, but only inline with base64 encoding. The reason for base64 encoding is that raw binary data breaks the xml standard and the encoded version contains only valid characters. This comes at the cost of having roughly 33% more data (factor 4/3), but you can actually open the file without "breaking" your editor. 

I attached the [vtuwriter_py.txt](https://github.com/phmkopp/vtu11/files/9828426/vtuwriter_py.txt) and an [example_py.txt](https://github.com/phmkopp/vtu11/files/9828506/example_py.txt) (you have to rename them as I can't directly upload .py files). I think the code is pretty cool as it's short and simple and uses the python standard library. As I said, it unfortunately can't write compressed raw binary, but the encoded compressed version should reduce the file sizes by a good amount already.

If this is useful for you I can create a new repository and may be able to implement the raw binary modes relatively quickly.

Let me know what you think.

Philipp

**Comment by JAWilliams123** [comment]
Hello Philipp,

Yes, I have a working solution and do not need you to update vtu11 at the moment :). Many thanks for the python code as well. I am mindful that you may have other things on your plate and would not trouble you with creating a new repository for the python code. Once again thank you so much for helping on this. 

Best wishes,
JW
