### ISSUE TITLE
When to use base64 ?

### ISSUE THREAD

**Issue by samayala22** [phmkopp/vtu11#49]
Hello, 

First of all, thanks for creating this library, it works very well and the code quality is excellent (learned a lot about composition principles and good use of r values references).

I don't have extensive experience with VTU files and after examining the ouput of the different writers I still don't see why one should use the `base64` writers instead of the `rawbinary`. Rawbinary always has smaller file sizes. However it does break the XML standard but is it *really* an issue ? 

Thanks for enlightening me.

**Comment by phmkopp** [comment]
Hello @samayala22 

no problem :) And thanks for providing feedback. I think there are a bunch of things that can be done better, but it is what it is for now.

To your question: my understanding is that raw binary breaks the xml standard, while base64 encoding does write valid characters (at the cost of roughly 4/3 times more data). So with raw binary, you say that your result file follows the xml standard (in the file header and implicitly by using the .xml extension), but it is not. If you are fine with that, let's say you only need to write and read files for your research work, then raw binary might be preferable. I'm using only compressed raw binary, for example. If you need valid xml, for whatever reason, then write base64.

Does that make sense?

**Comment by phmkopp** [comment]
And I haven't met anyone who needed base64 ... it's also kind of officially documented and supported by Paraview/Vtk (read and write), so I'd say it's rarely an issue, and when in doubt, use raw binary :)

**Comment by samayala22** [comment]
That clears things up. Thanks !
