### ISSUE TITLE
the version 1.2 of  vtu11.hpp has some problem

### ISSUE THREAD

**Issue by JWleo** [phmkopp/vtu11#54]
![capture1](https://github.com/phmkopp/vtu11/assets/32316654/637813b6-2298-41cf-af38-69836b3dc99d)

the code about  ``` CompressedRawBinaryAppendedWriter ```   need to add this sentence below , or it will not work when building the project
```c++
#ifdef VTU11_ENABLE_ZLIB
```

![capture2](https://github.com/phmkopp/vtu11/assets/32316654/b645c93c-24ee-45fc-8196-c9c61471b1c4)

**Comment by phmkopp** [comment]
It should work since `zlibWriter.hpp` includes `zlibWriter_impl.hpp` inside the `VTU11_ENABLE_ZLIB` conditional. Do you include `zlibWriter_impl.hpp` separately?

**Comment by JWleo** [comment]
no , i just have vtu11.hip in project downloaded from release web. i thought vtu11.hpp which has included all the code of *.hpp in your project

**Comment by phmkopp** [comment]
The `_impl.hpp` should not be included if you do not define `VTU11_ENABLE_ZLIB`. Alternatively, you could try the single-header version(s) from https://github.com/phmkopp/vtu11/releases/tag/v1.2.

**Comment by JWleo** [comment]
@phmkopp yeah i use the single-header version at first , and it's warning me all the time just like below 
![image](https://github.com/phmkopp/vtu11/assets/32316654/c48ac069-ce53-4439-93e1-dfa741cb99ff)

and i add code 
```c++
#ifdef VTU11_ENABLE_ZLIB
CompressedRawBinaryAppendedWriter::***
#endif
```

then the code can build successfully

**Comment by phmkopp** [comment]
Ahh, now I understood. I didn't notice the issue was related to the header-only version. I added the conditional as you suggested and updated the files for the v1.2 release. Thanks a lot for letting us know! :)
